// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteClipboardItem(arg1) {
  return window['go']['main']['App']['DeleteClipboardItem'](arg1);
}

export function EditClipboardItem(arg1, arg2) {
  return window['go']['main']['App']['EditClipboardItem'](arg1, arg2);
}

export function GetClipboardHistory() {
  return window['go']['main']['App']['GetClipboardHistory']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function TogglePinItem(arg1) {
  return window['go']['main']['App']['TogglePinItem'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
