// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearHistory():Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteClipboardItem(arg1:string):Promise<void>;

export function EditClipboardItem(arg1:string,arg2:string):Promise<boolean>;

export function GetClipboardHistory():Promise<Array<main.ClipboardItem>>;

export function GetSettings():Promise<main.Settings>;

export function HideWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function Quit():Promise<void>;

export function ShowWindow():Promise<void>;

export function TogglePinItem(arg1:string):Promise<boolean>;

export function UpdateSettings(arg1:main.Settings):Promise<void>;
